[constants]
    machine="Machine_1"	#Name of the machine being monitored (can't have spaces)

[adc]
    # uncomment the sensor / adc that you are using
    #adc_module = "ens160"
    adc_module = "sht40bmp280"

[sampling]
    sample_count = 5
    sample_interval = 0.2

[calculation]
   

[computing]
	hardware="Pi4"
	#hardware="Rock4C+"

[mqtt]
    broker = "mqtt.docker.local"
    port = 1883   #common mqtt ports are 1883 and 8883
    base_topic_template = "airquality_monitoring/{{machine}}"

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds
